version: 2
run:
  timeout: 5m

linters:
  exclusions:
    paths:
      - '(.+)_test\.go'
      - internal/completer
      - internal/repl/edit_command_buffer
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused 
    - gocyclo
    - goconst
    - misspell
    - unconvert
    - unparam
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    confidence: 0.8
    severity: warning
    rules:
      - name: exported
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
